### ISSUE TITLE
GRAB processing has left and right hand set to 0

### ISSUE THREAD

**Issue by sohananisetty** [IDEA-Research/Motion-X#6]
in [grab.py](https://github.com/IDEA-Research/Motion-X/blob/74c28149442e6b001e59047e00458cdd905870c3/mocap-dataset-process/grab.py#L60) you have set pose_left_hand and left_hand_pose to zeros even if they are present in the dataset. Why are you not using the dataset parameters?

**Comment by shunlinlu** [comment]
Hi,

Thanks for pointing out this problem. Since grab hand pose is 24 * 2(two hands) dim, which is not compatible with our representation smplx hand pose 45 * 2(two hands), thus using zeros here. For our latest human generation work [HumanTOMATO](https://github.com/IDEA-Research/HumanTOMATO), we instead use joints positions as our representations, which can be got from smplx_layer. The transformation code from these two representations will also be released in the HumanTOMATO code repo.

Grab dataset only has a small amount of cases, these hand pose does not affect the final effect much.

**Comment by sohananisetty** [comment]
The full pose parameter in the dataset did have the 45 hand representation. But if it does not effect it much then that's fine. Now that your human tomato code is released will you be releasing your dataset.
